version: '3'

services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:8000 main:app --reload
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "8000:8000"
    volumes:
      - ./:/root
